---
- name: Playbook
  gather_facts: true
  hosts: all
  tasks:
    - name: Check ssh service
      service: 
        name: ssh
        state: started

    - name: Check files inside of directory
      ansible.builtin.command: ls . 